"""create bugtrack relational schema

Revision ID: 18d131f67f3e
Revises: 
Create Date: 2026-07-20 19:34:43.229989
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '18d131f67f3e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bug_drafts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('flow_state', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('user_key', sa.String(length=191), nullable=False),
    sa.Column('session_id', sa.String(length=191), nullable=False),
    sa.Column('dify_conversation_id', sa.String(length=191), nullable=False),
    sa.Column('module', sa.String(length=255), nullable=False),
    sa.Column('operation_description', sa.Text(), nullable=False),
    sa.Column('environment', sa.String(length=64), nullable=False),
    sa.Column('issue_type', sa.String(length=64), nullable=False),
    sa.Column('search_keyword', sa.String(length=255), nullable=False),
    sa.Column('matched_record_id', sa.String(length=191), nullable=False),
    sa.Column('matched_snapshot', sa.JSON(), nullable=False),
    sa.Column('feishu_record_id', sa.String(length=191), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bug_drafts_dify_conversation', 'bug_drafts', ['dify_conversation_id'], unique=False)
    op.create_index('ix_bug_drafts_feishu_record', 'bug_drafts', ['feishu_record_id'], unique=False)
    op.create_index('ix_bug_drafts_status_updated', 'bug_drafts', ['status', 'updated_at'], unique=False)
    op.create_table('bug_route_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=191), nullable=False),
    sa.Column('active_app', sa.String(length=8), nullable=False),
    sa.Column('conv_a', sa.String(length=191), nullable=False),
    sa.Column('conv_b', sa.String(length=191), nullable=False),
    sa.Column('route_data', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel', 'session_id', name='uq_bug_route_session')
    )
    op.create_index('ix_bug_route_expires', 'bug_route_sessions', ['expires_at'], unique=False)
    op.create_table('bug_attachments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('draft_id', sa.Uuid(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=127), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('source_file_id', sa.String(length=191), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('feishu_file_token', sa.String(length=255), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['draft_id'], ['bug_drafts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('draft_id', 'sha256', name='uq_bug_attachment_draft_sha')
    )
    op.create_index('ix_bug_attachments_draft_status', 'bug_attachments', ['draft_id', 'status'], unique=False)
    op.create_table('bug_conversation_bindings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('draft_id', sa.Uuid(), nullable=False),
    sa.Column('namespace', sa.String(length=48), nullable=False),
    sa.Column('binding_key', sa.String(length=191), nullable=False),
    sa.Column('user_key', sa.String(length=191), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['bug_drafts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('namespace', 'binding_key', name='uq_bug_binding_key')
    )
    op.create_index('ix_bug_bindings_draft', 'bug_conversation_bindings', ['draft_id'], unique=False)
    op.create_table('bug_outbox',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('draft_id', sa.Uuid(), nullable=False),
    sa.Column('operation', sa.String(length=32), nullable=False),
    sa.Column('idempotency_key', sa.String(length=191), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['draft_id'], ['bug_drafts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('ix_bug_outbox_status_created', 'bug_outbox', ['status', 'created_at'], unique=False)
    op.create_table('bug_state_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('draft_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('from_state', sa.String(length=64), nullable=False),
    sa.Column('to_state', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('event_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['bug_drafts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bug_events_draft_created', 'bug_state_events', ['draft_id', 'created_at'], unique=False)
    op.create_table('bug_turns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('draft_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=64), nullable=False),
    sa.Column('structured_patch', sa.JSON(), nullable=False),
    sa.Column('dify_run_id', sa.String(length=191), nullable=False),
    sa.Column('idempotency_key', sa.String(length=191), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['bug_drafts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('ix_bug_turns_draft_created', 'bug_turns', ['draft_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bug_turns_draft_created', table_name='bug_turns')
    op.drop_table('bug_turns')
    op.drop_index('ix_bug_events_draft_created', table_name='bug_state_events')
    op.drop_table('bug_state_events')
    op.drop_index('ix_bug_outbox_status_created', table_name='bug_outbox')
    op.drop_table('bug_outbox')
    op.drop_index('ix_bug_bindings_draft', table_name='bug_conversation_bindings')
    op.drop_table('bug_conversation_bindings')
    op.drop_index('ix_bug_attachments_draft_status', table_name='bug_attachments')
    op.drop_table('bug_attachments')
    op.drop_index('ix_bug_route_expires', table_name='bug_route_sessions')
    op.drop_table('bug_route_sessions')
    op.drop_index('ix_bug_drafts_status_updated', table_name='bug_drafts')
    op.drop_index('ix_bug_drafts_feishu_record', table_name='bug_drafts')
    op.drop_index('ix_bug_drafts_dify_conversation', table_name='bug_drafts')
    op.drop_table('bug_drafts')
    # ### end Alembic commands ###

